### ISSUE TITLE
Karibou rover swallowed by Minmus

### ISSUE THREAD

**Issue by jberkman** [BobPalmer/Karibou#12]
I had a Karibou landed on Minmus and while I timewarpped at KSC it disappeared. In my logs:

```
[WRN 03:24:43.622] Vessel Minmus-Class Boar-Poodle-Karibou Mobile Base Mk I crashed through terrain on Minmus
[LOG 03:24:43.625] [Vessel Minmus-Class Boar-Poodle-Karibou Mobile Base Mk I]: Destroyed. No crews were aboard.
```

I'm guessing this is a bug inherent in the game, but maybe there's a collision mesh or something that exacerbates it?

Craft file: http://kerbalx.com/dunadirect/Minmus-Class-Boar-Poodle-Karibou-Mobile-Base-Mk-I
Last screenshot: http://www.dunadirect.com/uploads/2/7/0/3/27031688/6148263_orig.png

**Comment by BobPalmer** [comment]
Unless there's a part you can walk through, this would be a stock bug ;)

**Comment by jberkman** [comment]
I'll take your word for it, but it's happened twice now, the only times I left the vehicle with the legs deployed instead of wheels. When wheels were deployed, it was fine. Not enough data points to be conclusive, but there is definitely a trend there. i'm sure i've left it with legs deployed before, but maybe i hadn't used the crew cab?
